### ISSUE TITLE
Allow users to subscribe to our newsletter 

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/console#109]
If a user set `newsletter_subscription` as `true`, subscribe the user to our newsletter.

If an error is returned from subscribing operation, the console needs to handle the error internally, no need to show it on the UI.

**Comment by EiffelFly** [comment]
@xiaofei-du After looking up the old implementation we have at product-webiste, this feature may have a issue

- It need to use MAILCHIMP_API_KEY to access the Mailchimp API, this key need to be private.
  - For local dev we don't have any storage solution that can guarantee the safety of our key

## Soution

- We need to setup a serverless lambda function using cloudflare or aws lambda to act as the relay.
  - The console will send request to the serverless function, and the function will use stored API_KEY to access Mailchimp API

**Comment by xiaofei-du** [comment]
We will use another workaround to solve this.
