### ISSUE TITLE
RFI: Alert user they are leaving the unfinished form

### ISSUE THREAD

**Issue by EiffelFly** [instill-ai/console#111]
# Context

- Currently, if user mis click the previous page button, the form data will disappear

# Solution

- Popup alert to warn user

**Comment by iamnamananand996** [comment]
we can add a custom hooks for this, something similar to this [https://github.com/vercel/next.js/discussions/9662#discussioncomment-511835](https://github.com/vercel/next.js/discussions/9662#discussioncomment-511835)
please add it on which pages this will be required and will enable it for those pages.

**Comment by EiffelFly** [comment]
Yes, we already have similarly code in our cloud version but we haven't had time to merge it into open-source version, I will finish this task in a few days
