### ISSUE TITLE
Local model display bug

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/console#118]
VDP `make dev PROFILE=all`,

- Create a local model.
- Go to the model page, the `Settings` section display as a GitHub model.

![image](https://user-images.githubusercontent.com/66248476/178075277-852303b1-c0c2-4ec6-8123-b0289b9bd114.png)

**Comment by EiffelFly** [comment]
@xiaofei-du I can not re-produce this issue! Could you provide more information?

**Comment by EiffelFly** [comment]
@xiaofei-du I think this issue had been fix with the newest console
