### ISSUE TITLE
Bug: Hugging Face icon and name is not consistent with JSON Schema

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/console#153]
1. The Hugging Face logo is missing
2. Refactor `huggingface` -> `Hugging Face` (JSON Schema [link](https://github.com/instill-ai/model-backend/blob/f4d5f5e794dd3ed8ae71f8e6a92ed9ecd458fdee/config/init/instill/seed/model_definitions.yaml#L208))

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/66248476/178509708-5aae19cc-797c-4eb8-8571-73dd598278ff.png">

**Comment by EiffelFly** [comment]
@xiaofei-du This should have been fixed with 0.5.0-alpha

#152
