### ISSUE TITLE
Bug: wrong destination state display

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/console#210]
I created a destination that has a `STATE_ERROR` state.

Its state was shown correctly on the Destination page.
![image](https://user-images.githubusercontent.com/66248476/182658080-a3ff6bfa-2ec2-43c9-abf4-ed47fc46546d.png)

But click to the bad destination page, the state was wrongly displayed as gray icon.
![image](https://user-images.githubusercontent.com/66248476/182658498-57c26989-09a6-4459-a5b4-2241fa85fa5b.png)

**Comment by EiffelFly** [comment]
The table shows the pipeline used for this destination, so I think there might be a pipeline with the name "bad" too. Maybe we should change the "Overview" to "Pipeline used this destination" to make it clearer.
