### ISSUE TITLE
feat: make notification float on the screen

### ISSUE THREAD

**Issue by EiffelFly** [instill-ai/console#222]
# Context

- Current notification box limit the space of our design
- Current notification box is hard to find some time

# Solution 

- Make it floatable and stick to the top-right corner
- https://react-hot-toast.com/

**Comment by iamnamananand996** [comment]
Currently, I can see their are 2 component 

- ```<BasicProgressMessageBox />```
- ```<ProgressMessageBoxState />```

Implemented in the **design-system**, do we need to make this changes on **design-system**, or we  will add this new notification library into the components folder of **console**.

cc - @xiaofei-du

**Comment by EiffelFly** [comment]
@iamnamananand996 Please hold back this issue, we will have a major review and refactor of all out components including this one, so I will leave this issue here as a reminder but we can spend our effort on other tasks
