### ISSUE TITLE
Validate ID before sending request to backend

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/console#235]
For resource IDs, we follow the naming convention
```
The ID conforms to RFC-1034, which restricts to letters, numbers, and hyphen, with the first character a letter, the last a letter or a number, and a 63 character maximum. 
```
with Regex (need to check whether the following regex is correct)
```
^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$
```

Frontend can validate the IDs first before sending the request to backend

**Comment by iamnamananand996** [comment]
it seems like the is already done, as I can see the function is already added 2 month back. [https://github.com/instill-ai/console/blob/bb0e955a25ce6d9a18f549f1e7e35a79379a5763/src/lib/instill/validateResourceId.ts#L1](https://github.com/instill-ai/console/blob/bb0e955a25ce6d9a18f549f1e7e35a79379a5763/src/lib/instill/validateResourceId.ts#L1)
Does it required further changes also, then please let know here, I can make those changes,

**Comment by EiffelFly** [comment]
This is related to how we handle the form and we are working on it for our next version of console. @iamnamananand996 Thanks for your reminder, but this is also a wip issue and you can leave this issue as is right now
