### ISSUE TITLE
Remove `Setup guide` from `Deploy a model instance` section

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/console#247]
Since we have a `Setup guide` link when importing a model, we can delete the `Setup guide` in the `Deploy a model instance` section.

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/66248476/187005517-56c79cb8-4fb7-4d84-992c-6ceecaf4bcf3.png">

**Comment by EiffelFly** [comment]
@xiaofei-du 

I believe this one is pointing to https://www.instill.tech/docs/core-concepts/model#model-instance which is different from the import mode section which is pointing to each type of the model like https://www.instill.tech/docs/import-models/github.

Here is the typo about I didn't put the right link to deploy model instance.

**Comment by xiaofei-du** [comment]
OK, that makes sense.
