### ISSUE TITLE
Pipelines display in one line

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/console#261]
According to the design, all Pipelines and `+N` should be in one line. 

![image](https://user-images.githubusercontent.com/66248476/188452666-680c8925-9cac-4f44-b974-2eee1efd8aaa.png)

The current display
![image](https://user-images.githubusercontent.com/66248476/188451675-c6820fb7-7d6b-4410-8a03-fe7b990f68e1.png)

**Comment by EiffelFly** [comment]
@xiaofei-du this one is hard to replicate because it depends on your monitor configuration. The current solution will be adding more buffer into the calculation of this feature so it will break sooner to eliminate the additional line of the item.

Please check it again to see if the issue remain

**Comment by xiaofei-du** [comment]
The issue is fixed. but found a new bug.

See the below gif:
- on the `Source` page, and it shows `+2`
- click `Source` again, `+2` is gone.
- click other page and go back to `Source` page, it is fine.

![2022-09-07 at 0 18 55 - Amaranth Boar](https://user-images.githubusercontent.com/66248476/188756647-fb1bf0e8-03bf-4528-9362-4ad872fabc95.gif)
