### ISSUE TITLE
Deprecate old next/image with next/future/image

### ISSUE THREAD

**Issue by EiffelFly** [instill-ai/console#265]
# Context

- next/future/image has better configuration and it is easier to use

**Comment by iamnamananand996** [comment]
As the current version of application is ```"next": "^13.1.2"```, so I will not required any changes do be done.

For Next v13 users:

- I believe next/future/image is now the default Image component. So no additional work necessary! Just import and use

> ```import Image from 'next/image'```

For Next v12.3 users

- You don't need to add anything to the config to use future/image. The future image is now stable. Just use it directly by importing

> ```import Image from 'next/future/image'```

**Comment by EiffelFly** [comment]
@iamnamananand996 Yes, I think I already accomplished this issue, I will close this.
