### ISSUE TITLE
Fix typos in the UI

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/console#37]
1. Onboarding
- `Welcome to world's first AI-integrated pipeline dashboard` -> `Welcome to VDP console`
- `Receive the latest news from Instill AI: open source ...` -> `Receive the latest news from Instill AI for open source ...` 
![image](https://user-images.githubusercontent.com/66248476/174918280-0d12d1a0-05bd-4336-b8a1-8212cb6f3954.png)

2. Set up model left part
- `Select a existing online model` -> `Select an existing online model instance`
- `Source type*` -> `Online model instances*`
<img width="721" alt="image" src="https://user-images.githubusercontent.com/66248476/174867170-4d73f9fa-d4ef-4cba-82d4-62944e5d9c63.png">

3. Set up model right part
Just use the above screenshot as an example. I think we should replace all `Name` fields with `ID`. This is due to we have adopted the Google AIP Practise. E.g., If I list all models, this is the response. The field is actually `ID`, not `Name`.
 
```json
{
    "models": [
        {
            "name": "models/mobilenetv2",
            "uid": "343bf231-2a00-441b-adb2-c8fdc6a525cc",
            "id": "mobilenetv2",
            "description": "⚗️ MobileNetV2 trained on ImageNet for image classification",
            "model_definition": "model-definitions/github",
            "configuration": "{\"html_url\": \"https://github.com/instill-ai/model-mobilenetv2\", \"repository\": \"instill-ai/model-mobilenetv2\"}",
            "visibility": "VISIBILITY_PUBLIC",
            "user": "users/local-user",
            "create_time": "2022-06-21T16:59:35.118347Z",
            "update_time": "2022-06-21T16:59:35.118347Z"
        }
    ],
    "next_page_token": "",
    "total_size": "1"
}
```
Note that here I just use one screenshot as an example, there are other pages with `Name` fields to be replaced, such as the pipeline name in Pipeline tab or model name in Model tab.

**Comment by EiffelFly** [comment]
@xiaofei-du I have some questions

- When it comes to choosing existing model, it looks like we want user to choose a model-instance here, can he just choose a model but not specific a model-instance to deploy?
- If the above is true, what if user encounter some model-instance with the same id, you could only specific different model-instance with model-instance-name like `models/model1/instances/cpu` and `models/model1/instances/cpu`

**Comment by xiaofei-du** [comment]
> @xiaofei-du I have some questions
> 
> * When it comes to choosing existing model, it looks like we want user to choose a model-instance here, can he just choose a model but not specific a model-instance to deploy?

The current design only allows a user to choose an *online* model instance. The dropdown list shows all the existing online model instances with the format `{model_id}/{model_instance_id}` (see the screenshot).
![image](https://user-images.githubusercontent.com/66248476/175013532-2258e1a7-9b9d-4ee2-afc3-5045f678b051.png)

A better design may be to allow the user to pick one model instance among all existing model instances no matter it is online or offline. 
![image](https://user-images.githubusercontent.com/66248476/175015914-89855631-8363-4ad6-89b0-1499b06d2532.png)

But we can iterate it later.

**Comment by EiffelFly** [comment]
@xiaofei-du I agree with you about the proper design, that is much clear! and easier to navigate!

And sorry that I misunderstand what you try to say of this point

> Just use the above screenshot as an example. I think we should replace all Name fields with ID

Because your screenshot have popup selection on the right side, I misunderstand that you try to focus on the right side.

This is clear enough, I will refactor all the name filed to ID field

**Comment by xiaofei-du** [comment]
@EiffelFly, I forgot to add the following typo:

1. `right half` Set up model / Deploy a model instance
  - `Source type*` -> `Model instances*`

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/66248476/175520083-0cb3bca6-e2f0-43a1-98db-e39ada04a3fa.png">

**Comment by EiffelFly** [comment]
@xiaofei-du, I Will implement all the related hot-fix tomorrow

**Comment by xiaofei-du** [comment]
> This is clear enough, I will refactor all the name filed to ID field

Can you refactor the field from `Id` to `ID` on all relevant pages?
![image](https://user-images.githubusercontent.com/66248476/176813635-c16f3572-aee9-4ef1-b68c-bdeea8643332.png)

Let me reopen this issue.
