### ISSUE TITLE
Cookie not persisting user

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/console#47]
When I do
1. `make dev PROFILE=all` and go to console 
2. fill the onboard form
3. `make down`  
4. Repeat step 1,  redirected to `http://localhost:3000/onboarding` page

**What happened**
I need to re-onboard again.

**What to expect**
Skip the onboarding form and be onboarded automatically with a persistent cookie

**Screenshots for debugging**
after step 2
<img width="1092" alt="Screenshot 2022-06-24 at 11 08 44" src="https://user-images.githubusercontent.com/66248476/175518689-25726580-f636-4a4b-a0f9-19ea6fda3566.png">
after step 4
<img width="1090" alt="Screenshot 2022-06-24 at 11 10 00" src="https://user-images.githubusercontent.com/66248476/175518695-878740dc-ea9b-4596-abc9-86a8cbeed6d2.png">

**Comment by xiaofei-du** [comment]
Maybe the problem is not about the cookie, but about implementation.

Go to `localhost:3000` will **always** be re-directed to onboarding automatically.

**Comment by EiffelFly** [comment]
@xiaofei-du You are right, I had fixed this issue at #49
