### ISSUE TITLE
Disable model testing when model instance is not online

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/console#72]
Currently, we allow users to test a model instance even if it is not online. 

Can we add the logic checking that if a model instance model is not online, disable the testing feature?

![screencapture-localhost-3000-models-mobilenetv2-2022-06-29-15_09_11](https://user-images.githubusercontent.com/66248476/176457676-caa7a2ce-7e53-472b-ae67-b8b76cfe57f2.png)

**Comment by EiffelFly** [comment]
@xiaofei-du I have added some info when disabling the testing feature, what do you think?

![截圖 2022-07-01 上午9 42 00](https://user-images.githubusercontent.com/57251712/176806025-ebaf2ffb-fd01-4e8b-9c66-43c128b7bb7b.png)

**Comment by xiaofei-du** [comment]
Sure, and also refactor the following:
- `Testings` -> `Testing`
- `Create and upload a zip file that contains all the model files from your computer` -> `Upload an image file from your computer to test the model instance`
